{
 "title": "Test1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperatura",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\"\nFROM \"mqtt_consumer\"\nWHERE \"topic\" = '/sensors/dht11' \nORDER BY time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Nivel de agua",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\"\nFROM \"mqtt_consumer\"\nWHERE \"topic\" = '/sensors/ultrasonic' \nORDER BY time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "pH",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\"\nFROM \"mqtt_consumer\"\nWHERE \"topic\" = '/sensors/potentiometer' \nORDER BY time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") as temperature\nFROM \"mqtt_consumer\" \nWHERE \"topic\" = '/sensors/dht11'\nAND $timeFilter \nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Nivel de agua",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") as water_level\nFROM \"mqtt_consumer\"\nWHERE \"topic\" = '/sensors/ultrasonic' \nAND $timeFilter \nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "pH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "SELECT mean(\"value\") as pH\nFROM \"mqtt_consumer\"\nWHERE \"topic\" = '/sensors/potentiometer' \nAND $timeFilter \nGROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}