services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1885:1885"  # Puerto MQTT
      - "9001:9001"  # Websocket (opcional)
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/pwfile:/mosquitto/config/passwd
    restart: always

  influxdb:
    image: influxdb:1.11.8
    container_name: influxdb
    ports:
      - "8086:8086"  # API HTTP de InfluxDB
    environment:
      - INFLUXDB_DB=piscina
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      
    volumes:
      - influxdb_data:/var/lib/influxdb2      
    restart: always

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mqtt
      - influxdb
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3001"  # Interfaz web de Grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/defaults.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    depends_on:
      - influxdb
    restart: always

volumes:
  influxdb_data:
  grafana_data: